
### 1.1 - Record reactions to joke #1

POST localhost:8080/v1/joke/1/reaction
Content-Type: application/json

[
  {
    "date": "2020-12-31",
    "reaction": 9
  },
  {
    "date": "2021-01-06",
    "reaction": 8
  },
  {
    "date": "2021-01-11",
    "reaction": 9
  }
]

### 1.2 - View historical reactions to joke #1

GET localhost:8080/v1/joke/1/reaction
