
###

POST localhost:8080/joke/1/reaction
Content-Type: application/json

{
  "date": "2020-12-31",
  "reaction": 9
}

###

POST localhost:8080/joke/1/reaction
Content-Type: application/json

{
  "date": "2021-01-06",
  "reaction": 8
}

###

POST localhost:8080/joke/1/reaction
Content-Type: application/json

{
  "date": "2021-01-11",
  "reaction": 9
}

###

GET localhost:8080/joke/1/reaction
