
### 3.1 - Record reactions to joke #3

POST localhost:8080/v1/joke/3/reaction
Content-Type: application/json

[
  {
    "date": "2020-12-31",
    "reaction": 2
  },
  {
    "date": "2021-01-06",
    "reaction": 1
  }
]

### 3.2 - Reassign joke #3

PUT localhost:8080/{{v}}/joke/3/owner
Content-Type: application/json

{
  "since": "2021-01-12",
  "name": "Jan"
}

### 3.3 - Record further reactions to joke #3

POST localhost:8080/v1/joke/3/reaction
Content-Type: application/json

[
  {
    "date": "2021-02-07",
    "reaction": 7
  },
  {
    "date": "2021-02-12",
    "reaction": 9
  },
  {
    "date": "2021-03-01",
    "reaction": 8
  }
]

### 3.4 - View historical reactions to joke #3

GET localhost:8080/{{v}}/joke/3/reaction
