
###

GET localhost:8080/jokes

###

POST localhost:8080/jokes
Content-Type: application/json

[
  {
    "text": "Two antennas had a wedding"
  },
  {
    "text": "Fish hit a wall"
  }
]

###

POST localhost:8080/joke/1/reaction
Content-Type: application/json

{
  "oneToTen": 1
}

###

POST localhost:8080/joke/2/reaction
Content-Type: application/json

{
  "oneToTen": 2
}
